package com.tuanlinh.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FolderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFolderAllPropertiesEquals(Folder expected, Folder actual) {
        assertFolderAutoGeneratedPropertiesEquals(expected, actual);
        assertFolderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFolderAllUpdatablePropertiesEquals(Folder expected, Folder actual) {
        assertFolderUpdatableFieldsEquals(expected, actual);
        assertFolderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFolderAutoGeneratedPropertiesEquals(Folder expected, Folder actual) {
        assertThat(expected)
            .as("Verify Folder auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFolderUpdatableFieldsEquals(Folder expected, Folder actual) {
        assertThat(expected)
            .as("Verify Folder relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFolderUpdatableRelationshipsEquals(Folder expected, Folder actual) {}
}
