version: '3.8'

services:
  alpine:
    image: alpine:latest
    container_name: alpine_with_tools
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "apk update && apk add sudo docker docker-compose && /bin/sh"
