# Build on Node 18-alpine
FROM node:18-alpine

# Create app directory
WORKDIR /tuan-user/du-an/simple-nodejs-app

# Bundle app source
COPY tuan.js .
# COPY . .

# Start the app
CMD [ "node", "tuan.js" ]